/var/lib/condor/execute/slot1/dir_1215657/run_python.sh: /var/lib/condor/execute/slot1/dir_1215657/python/bin/kaggle: /var/lib/condor/execute/slot1/dir_1969957/python/bin/python3: bad interpreter: No such file or directory
/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "analyze_data.py", line 18, in <module>
    main(sys.argv[1])
  File "analyze_data.py", line 12, in main
    data = load_data(file_path)
  File "analyze_data.py", line 5, in load_data
    return pd.read_csv(path)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/var/lib/condor/execute/slot1/dir_1215657/python/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'themes.csv'
